// src/jsx/App.jsx
import { Stack } from '@mui/material';
import WebServiceModal from './core/components/WebServiceModal';
export default function App() {
    const config = {
        url: 'https://jsonplaceholder.typicode.com/posts/{id}?test=true',
        httpMethod: 'POST',
        useProxy: true,
        httpAuth: "BASIC",
        bodyParams: "{userName:password}",
        userName: "userName",
        userPassword: "userPassword",
        headerParams: [
            {
                name: 'New',
                type: 'string',
                value: 'application'
            }
        ],
        multipartParams: [
            {
                name: "post",
                type: "file",
                value: "fe"
            }
        ],
        contentType: 'multipart/form-data'
    };
    return (<>
      <Stack className='rest-import-ui'>
        <WebServiceModal restImportConfig={config} language='en'/>
      </Stack>
    </>);
}

// examples/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';


declare const RestImport: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-app';

  ngAfterViewInit(): void {

    const reactUI = RestImport({
      dom_id: '#rest-import-ui',
     language:"fr",
     config: {
      url: 'https://jsonplaceholder.typicode.com/posts/{id}?test=true',
      httpMethod: 'POST',
      useProxy: true,
      httpAuth: "BASIC",
      bodyParams: "{userName:password}",
      userName: "userName",
      userPassword: "userPassword",
      headerParams: [
        {
          name: 'New',
          type: 'string',
          value: 'application'
        }
      ],
      multipartParams: [
        {
          name: "post",
          type: "file",
          value: "fe"
        }
      ],
      contentType: 'multipart/form-data'
    },
    })


  }
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 mx-auto my-3">
            <button class="btn btn-lg btn-outline-primary btn-sm" (click)="enableFullScreen()">Full Screen</button>
        </div>
        <div class="col-md-3 mx-auto my-3">
            <button class="btn btn-lg btn-outline-primary btn-sm" (click)="openModal(1)">Popup Modal</button>
        </div>
        <div class="col-md-3 mx-auto my-3">
            <button class="btn btn-lg btn-outline-primary btn-sm" (click)="openModal(2)">Pre Populate Screen</button>
        </div>
        <div class="col-md-3 mx-auto my-3">
            <button class="btn btn-lg btn-outline-primary btn-sm" (click)="openConfigModal()">Config Modal</button>
        </div>
    </div>
    <div class="row" *ngIf="fullScreen">
        <div class="col-md-12">
            <app-fullscreen></app-fullscreen>
        </div>
    </div>
    <div id="configModalUI"></div>
</div>
