// examples/angular-app/src/app/app.component.ts
import { Component, Input } from '@angular/core';

import { NgbModal, NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { ModalComponent } from './modal/modal.component';
declare const RestImport: any;
declare const configImport: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  constructor(
    private modalService: NgbModal,
    public activeModal: NgbActiveModal
  ) {}
  public fullScreen: boolean = false;
  enableFullScreen() {
    this.fullScreen = !this.fullScreen;
  }

  openModal(type: number) {
    const modalRef = this.modalService.open(ModalComponent, {
      size: 'xl',
      centered: true,
    });
    if (type == 1) {
      modalRef.componentInstance.configtype = false;
    } else {
      modalRef.componentInstance.configtype = true;
    }
  }

  openConfigModal() {
    const reactUI = configImport({
      dom_id: '#configModalUI',
      language: 'en',
    
      config: {
        proxy_conf: {
          base_path: 'http://localhost:5000',
          proxy_path: '/restimport',
          list_provider: '/get-default-provider',
          getprovider: '/getprovider',
          addprovider: '/addprovider',
        },
        default_proxy_state: 'ON',
        oAuthConfig: {
          base_path: 'https://www.wavemakeronline.com/studio/services',
          project_id: 'WMPRJ2c91808888f5252401896880222516b1',
          list_provider: '/oauth2/providers/default',
          getprovider:
            '/projects/WMPRJ2c91808888f5252401896880222516b1/oauth2/providers',
          addprovider:
            '/projects/WMPRJ2c91808888f5252401896880222516b1/oauth2/providers',
        },
      },
    });
  }
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 mx-auto my-3">
            <button class="btn btn-lg btn-outline-primary btn-sm" (click)="enableFullScreen()">Full Screen</button>
        </div>
        <div class="col-md-3 mx-auto my-3">
            <button class="btn btn-lg btn-outline-primary btn-sm" (click)="openModal(1)">Popup Modal</button>
        </div>
        <div class="col-md-3 mx-auto my-3">
            <button class="btn btn-lg btn-outline-primary btn-sm" (click)="openModal(2)">Pre Populate Screen</button>
        </div>
        <div class="col-md-3 mx-auto my-3">
            <button class="btn btn-lg btn-outline-primary btn-sm" (click)="openConfigModal()">Config Modal</button>
        </div>
    </div>
    <div class="row" *ngIf="fullScreen">
        <div class="col-md-12">
            <app-fullscreen></app-fullscreen>
        </div>
    </div>
    <div id="configModalUI"></div>
</div>

// src/App.tsx
import { Stack } from '@mui/material'
import WebServiceModal from './core/components/WebServiceModal'
import { restImportConfigI } from './core/components/WebServiceModal'


export default function App() {
  const config: restImportConfigI = {
    proxy_conf: {
      base_path: "http://localhost:5000",
      proxy_path: "/restimport",
      list_provider: "/get-default-provider",
      getprovider: "/getprovider",
      addprovider: "/addprovider",
    },
    default_proxy_state: "ON",
    oAuthConfig: {
      base_path: "https://www.wavemakeronline.com/studio/services",
      list_provider:
        "/oauth2/providers/default",
      getprovider:
        "/projects/WMPRJ2c91808888f5252401896880222516b1/oauth2/providers",
      addprovider:
        "/projects/WMPRJ2c91808888f5252401896880222516b1/oauth2/providers",
    },
  }

  return (
    <>
      <Stack className='rest-import-ui'>
        <WebServiceModal restImportConfig={config} language='en' />
      </Stack>
    </>
  )
}
